language: python
python:
  - "2.7"
os: osx
osx_image: xcode6.4
before_install: |
  brew install python;
  virtualenv venv -p python;
  source venv/bin/activate;
install: cat requirements.txt | xargs -n 1 -L 1 pip install
script: pyinstaller biomhandler.spec