language: python
python:
  - "2.7"
os: osx
osx_image: xcode6.4
before_install: |
  if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    sudo -H easy_install pip
    sudo -H easy_install virtualenv
  fi
install: cat requirements.txt | xargs -n 1 -L 1 pip install
script: pyinstaller biomhandler.spec