os:
- linux
- osx
osx_image: xcode6.4
before_install: |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    HOMEBREW_NO_AUTO_UPDATE=1 brew install python;
    pip install virtualenv;
  fi
  virtualenv venv -p python;
  source venv/bin/activate;
install: cat requirements.txt | xargs -n 1 -L 1 pip install
script: pyinstaller biomhandler.spec
deploy:
  provider: releases
  api_key:
    secure: YItBEq8drhlDmtKkni6y3qg9rpr6pIspaCDLL9ab0EJiOj3u7Feo54bt3SxAjVBwvB/fyIXlraga2WYwrBfN3FeEEnkStQPy/+gIk8g09+YKMm1EI9sIcjoPZurFHOqZu27WZ7DkmJ6jAya+Ifev55KRHBgWwa8lq7UDUsWq0QSvktgrdyX4omNvhxA3cRdRhvrB7EcaqtCnrWN8Lqkz6yYfnCzXeOQFFyDwbjbtL2tSTf28JJtLuH2UuCed7gZFPa8nkdbZC0QRrVTFIIdjA9/GGZg7pOgMlHcxkMWGrjww5GGENfiIvKFEop4xGsiQQd5kCcSrCvB5GadBy3JYUJWhz7M0ZATohkn6Cgyp7sIGUbWwzwj7WZsBn8aJv8oSIRmOX7orUONS1jlw90aj77cBoT5LvYnFAWw2jZ7n/oPfN/ISz5za5RwRq9ldd4LAVHZiTGFXy3UzJ0zEaIcNL/Rjx1J8eTXvEGAm+ohY1JTyWH4n2EFtdlv8H62r0suZ/8dKu+4bSLIO6H/NZgwcqIpITy9DWs1LNzY6velbpavP0m3us0UX3GIUI2NeDQO8bpO+ia3MK2myzdAUig4dTU/t9V/RdtUxo+6gp3F47HMAvUdA1RqzSLH8E771Z1VeoAFSy5tQmVFnNM6xmhxZbYOlB1754HIgagI3Lxn5F8o=
  file: "/build/PhinchApp/biomhandler/dist/biomhandler"
  on:
    repo: PhinchApp/biomhandler
    tags: true
