os:
- linux
- osx
osx_image: xcode6.4
before_install: |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    HOMEBREW_NO_AUTO_UPDATE=1 brew install python;
    pip install virtualenv;
  fi
  virtualenv venv -p python;
  source venv/bin/activate;
install: cat requirements.txt | xargs -n 1 -L 1 pip install
script: pyinstaller biomhandler.spec
deploy:
  provider: releases
  api_key:
    secure: lFLMl3XJZmoa8qxpaI05/7t40G489WBG9tClUVmiwkC34iRVBAsgK3sCXZiWuOSMjqpovXSc3o16SF67QOvvrfhthHuOlODrkh0DQDBdAyOgVQjQzqd4+ZjoRX51m6U/IC8T78ORE/R/D4H5NO4rzyW0cxXvZhR7/zHDwMH5YHx8oWbxxPY6FaLgT/38KCPZN+QJANW7KhBXeTp4H5yaFz5dxNuukukvidYSUN3oNkytQmHGuCv1d1w67eRG99rkRWs5kTRIuJc4Y8ivZcjWtFmhcmJ1aViM8JlP+XMYer7I69Legv8SRLkyq3gI39S2ce/9IFKPJn0YOJUAPmAnH31XyCqF24YyY7pRfJyz1RK0y6Q1dOqAbqRXtVFnLiTXuHzkMnHd7eaNSnfs8b7/w1ZWt6WO0aGXJ5l6dZHcV7+fn5Rpi6WjmhpdWA/uHrqqcicsEzsLjOkQFKCDSVnsml8vN0vXk6jE2NZdG0rwy2sN0DGt62jwuN6CDZm0I+LMpYU3jl5xeKHGw/dy72BqUFPdSV5e584MqmsUIJKEkD4tJtjALrthf4AOIi4lpvmYx4Za1xxVpi59FrE8mF2qVr44U7Av9SiiYpq4w5l1HXrOfLCg/BkRCiB+1L5MNqHohjCBmdrJwn0ICHGpuUBONrJr7Ge0eX7qqU20cIqzwWc=
  file: dist/biomhandler
  skip_cleanup: true
  on:
    tags: true
    repo: PhinchApp/biomhandler
