os:
- linux
- osx
osx_image: xcode6.4
before_install: |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    HOMEBREW_NO_AUTO_UPDATE=1 brew install python;
    pip install virtualenv;
  fi
  virtualenv venv -p python;
  source venv/bin/activate;
install: cat requirements.txt | xargs -n 1 -L 1 pip install
script: pyinstaller biomhandler.spec
deploy:
  provider: releases
  api_key:
    secure: hbOblPMX7Fw3sPKQDoCj4O/lRTPGC1pGFwXM6Bxgxrrpmbl5RKlUJUxOCO/ByttETxXZRxiqwJnLcTat2pjF3Cz+y+B8QKiQJ0h1AOC+8SiiP7FG0yhUZL4pJF4zTwkq+1CS472D0YGfhjJVm8l+XqX5bgzOHxk6DHkOjzDKOWgZS44I9I511UE0E//+Sbf9Rz+qPKeLnC9FszzkUv66xOMO4yC71e6wkzuCtdhucU0td26kXorM4A6T+BL9NODX7SYRPI+qtakdPmDzKmHCFZGs4lUPngUO26PeMyAvM2O7MctB8fNwk5k/8qHO/79T+s1TjLy3DonsU4F534WZMsKgpwZV9wGh7a/0Qo9JF7plQBi1iduP7Howw47cCrUmwHDqlpqdZPJtLcbvHDMZNNw0H6VgJz3ghcJqZqgCbHUofXb6APm3b4e/TqPHoLJbi5i0Jt2ynNalbeS31sit/6wL2ksj2NJHvXNOOv6TnvPWrxyVZ/IzfH1beczMemJmEKRzOwkeI1vsKGLdNhbnuydm8rOBIBLj8OniSN8tUn7htfUCFb7FZnO4MxgMLaRqvSOox9G7QwkLbzWHbnDh1LatdFrOvjfoM7OiZn+b5/sBdxryM3DtGVrtIzH5HqXxsoJdh5KOL4YgactCvexrHIN7a1SrMBPwIHcHDYAfHGk=
  file: "/build/PhinchApp/biomhandler/dist/biomhandler"
  on:
    repo: PhinchApp/biomhandler
    tags: true
