os:
- linux
- osx
osx_image: xcode6.4
before_install: |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    HOMEBREW_NO_AUTO_UPDATE=1 brew install python;
    pip install virtualenv;
  fi
  virtualenv venv -p python;
  source venv/bin/activate;
install: cat requirements.txt | xargs -n 1 -L 1 pip install
script: pyinstaller biomhandler.spec
deploy:
  provider: releases
  username: "jproctor@udel.edu"
  password:
    secure: MHP275CmjiW/cHjmas2EiYQ9zJ+YQUevtgq6cSml8nfkiS0/hmsFJ1sNSan9VKgJblHm9gsLKe8Z4oYPJzLmrXzrFw0vaL94FIkO+esNWz41/Cw/ZyVDlHOCqzaG+lhULq4sbN0BdLsVAQQ43G8D0mVYLC2Uspbz9cjDbIuQX7eG8pj/aoepO8XFVl5NekzdGcsgiBZ3M1ngolNmN4kUakLhlr5O3kqvaq5pL3k5mrHcTkN3aMGfzktnObTkA4CFWt7h2JUEW06asjIe4nMdvps6+LrYB57LQlc2qOtQfV0CVoxGwgfpUQ8p5lkWnT3wHPlFLh17Rznb5f85Iq++PNpY8kSrB+r7708zn56CjZBQxkLfVU6PdU6M9vFiN4E2x1nD5skfbf/7t/m+Nvk0xwczlBR74n6M9YTlqxe2zPR1Pc4yLJKk8okd2iZAgQXOmtTjJqSb5uWisTOlT4+MUdpZ/hfn5sYO+zrJEd51wyohocOwP6G+p5ED+TcHKU9GOVJxQYsUM5li/sBdxPwanEPr+up2LWOxMXp2UrOK0hazssCdGhDRlBUUQILQF1GXi3fO5eQexheuUCAkHLC7RuCRRxH2d2esPrjPRn2WfNnKkzeZCpohGwJXffv8xMiY8rz7r8AYdIakwmUKKWO2UL65lNDKSJfupQWENncwTxU=
  api_key:
    secure: hmROIWSHqMpX3PXrqVCLKjhiT9Lgr4dCiXca63wYFcgvwesCY9tM29sdjC9jm9U9+Y0Advh6h7gzxmgcbmoPMfV/dTmSU6uWtvYzBqVmVWzDjM5Bl4JfocZLNupNz6/Tiu7EwCtmRP43ehKBh823eTxMerTRGP9+zGESVYI7QTNLV3X4LFfCsT9IrsMBCbIPTTGO/ApDqqHNOy9zUpHgC/zSjY0E41SNTZeW7WTf2SkZa1V7Azp6MzpQyrXhjatxGLfhGjrByRJNyPtvS0o/6KO7LDr9KXL7jvKTl1rbCoCnG05lrX201iQKTHTWXwcdJm9QrNoCiijP2c4ZL4IRCct0TWQJYIAecgHHeHCtpddQIwaXuBITo4EYDZBU9jWx5n/ZPUAve5yWfxSWnxsW5QfplYqYMhjgN48HaR1xAN1QVku11AgsQs4Cc7gaW/UQZu5Ps/Hvrf1xO+k7m3KXRb9sBqsJ9I0nGeeRpOADzWXziFuJ1F03IlvrHlNd4vhNFDP9e1e2/UeWelrjxQG+VgHJuWw/FSXno/+I2LXvHen7ilO67KmkS3fKnQQZ6aCPjhqvbWnkTKbc7qax/2BBMQ86JVyArVxY8iu2D0PtoVt7XL1pXjEfguE2JbmRLbptjFa8vcWqQXLwbPuz/DzyarKxs7/txOYKgINB4yEN0Zs=
  file: dist/biomhandler
  on:
    repo: PhinchApp/biomhandler
