os:
- linux
- osx
osx_image: xcode6.4
before_install: |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    HOMEBREW_NO_AUTO_UPDATE=1 brew install python;
    pip install virtualenv;
  fi
  virtualenv venv -p python;
  source venv/bin/activate;
install: cat requirements.txt | xargs -n 1 -L 1 pip install
script: pyinstaller biomhandler.spec
deploy:
  provider: releases
  api_key:
    secure: lGhIXOnnsLbp81/5LE3QTMWAJD9qwFLZGwIC84XscI6T/Ba8Ip/lOIWUlESop9Q3q/vNZF3J3vwV4hfqXdKVAxiWq69UxHKRuu3NG+tl9E7ZydGWfel4Bm1+Dj/9KrjPzkG+qV9kq+uPKnKlKouXigKZedaEHAH03/BGeoZ7Gql02Evv1JWgANgSLbDE3fVsNqM92Ap/j2jn47HERFsDyWhj+fvvYh47ZXCO6Z+RSSuEqJE573BtBYyM+RSL4UjysE5IblcmROJaL+WFeISibpvQurzrgXXZmN6L+ZdB/BOvjApA6FIPdwQwcog/vA7ntr9/Ph0l1CCTzriQR8MBEBnMkdL6rVeEJ5juqN6QgfNhQk9NwMK0Z1gaNO/lk+zsqcQwgYfQvEW7aNPt49b/shMA7TJITzIHbhDTuqFftr1LGDefQG3bD+wMA8jwf7a2r/NXdknnl74EEQL4O2Y2pZnkchQ7Z3Nb/gOmYVYjpBW521QAlMR5t9DJMCydS0Ze2Xxg7GIbScdWm7dDcuKlTXHxK6xl1yRXmqa8CxH2Dl67Y81Ugr7HeUnoQvCbCn6ML/m9+wfNzeuA6A+PKt270LWyhqUimE5aolCWd5GeXKQjAgFrEmdKE94ypM7aD24Pbj7fipCSRDgcxyT+x4valnLyxcqkRiOI8VxabAwBso4=
  file: dist/biomhandler
  skip_cleanup: true
  on:
    repo: PhinchApp/biomhandler
