os:
- linux
- osx
osx_image: xcode6.4
before_install: |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    HOMEBREW_NO_AUTO_UPDATE=1 brew install python;
    pip install virtualenv;
  fi
  virtualenv venv -p python;
  source venv/bin/activate;
install: cat requirements.txt | xargs -n 1 -L 1 pip install
script: pyinstaller biomhandler.spec
deploy:
  provider: releases
  api_key:
    secure: "VuECSgG6Bo2nwAlVt0kIf+YgcdVzri5IbqnG+03PzWrKIeeRJ5kEutWXOP/x+zyHWSGkIEBWKNtNZ/pBMY5wHaoKyFfcPep5T9RuK1IbRB96mdUNlYVulsN465PaffC5zFcXfOzABRY9+ROLXBbW6/17w1CQexX6hEQuzvAA9hnixNb+xh/zkvl+5QrQNrifj8zTjBKB0n1/NmbSqitIjebSF5CjmAIAntwPP3e274JimrIEFXbeb/BlwR/CXEz09JTOFxSKqC+pvll8MWN9uYS+NHGSqkTBS/dtsqqkslYU87ONg/UE9jvmyCpCD3CphhsKIkVCfVTBca0pugOinGkzj/W1IacydiqRHzmos6nvUZDJ4hwkePTri/4I1d2MUa7l2dyFZFH5XMWhcSlVQgMwcxeW0+jc9zfYTcP5VDIy5INOdVMuwRlPlXBrDr8SczCTeUQLvJTGa9VEy8EJFq9IoP1tu7LvXufSE2vGDRiXu/39mMXl4h0PanP4fqvAUGR5Hjftf0gYWjP8rIVL4IyOgL0B9IVXoyfvtstVV8Wbac6cIu/ONM8GBIXiZ/ouSnteNU0OsL2sF4qAzh2tmVU0HASkYTDNv3i13Mm8s8l42OXy5HsiqY6IC7COX/9IgBMn378310Z9FxtqQrVB9CSvV2RVZzhCgpvbq0cU534="
  file: "/build/PhinchApp/biomhandler/dist/biomhandler"
  on:
    repo: PhinchApp/biomhandler
    tags: true
